// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49jnekE41-4YVSqLPPT6pxbsCd2yegZs',
    appId: '1:344590144534:web:ed54b3d57d3ed8f1129137',
    messagingSenderId: '344590144534',
    projectId: 'ryan-first-project-87fbd',
    authDomain: 'ryan-first-project-87fbd.firebaseapp.com',
    storageBucket: 'ryan-first-project-87fbd.firebasestorage.app',
    measurementId: 'G-8PL4VN8S00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxrKfVfYWuNZnXji5MJKMyK12vQrE7Ow',
    appId: '1:344590144534:android:0b2d0af6afcf2a95129137',
    messagingSenderId: '344590144534',
    projectId: 'ryan-first-project-87fbd',
    storageBucket: 'ryan-first-project-87fbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPWnqdfpnWWgdrGs5Gif7hrrLymgq4os',
    appId: '1:344590144534:ios:95a7f25145ad3b41129137',
    messagingSenderId: '344590144534',
    projectId: 'ryan-first-project-87fbd',
    storageBucket: 'ryan-first-project-87fbd.firebasestorage.app',
    iosBundleId: 'com.example.thirdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrPWnqdfpnWWgdrGs5Gif7hrrLymgq4os',
    appId: '1:344590144534:ios:95a7f25145ad3b41129137',
    messagingSenderId: '344590144534',
    projectId: 'ryan-first-project-87fbd',
    storageBucket: 'ryan-first-project-87fbd.firebasestorage.app',
    iosBundleId: 'com.example.thirdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB49jnekE41-4YVSqLPPT6pxbsCd2yegZs',
    appId: '1:344590144534:web:e2b6489273f57b8e129137',
    messagingSenderId: '344590144534',
    projectId: 'ryan-first-project-87fbd',
    authDomain: 'ryan-first-project-87fbd.firebaseapp.com',
    storageBucket: 'ryan-first-project-87fbd.firebasestorage.app',
    measurementId: 'G-351V7TM28B',
  );
}
