// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTus1S9ghn4A06IAsXUgZkqVzlF6P-CeU',
    appId: '1:134493834023:web:dadd205b998e826f45f702',
    messagingSenderId: '134493834023',
    projectId: 'love-88094',
    authDomain: 'love-88094.firebaseapp.com',
    storageBucket: 'love-88094.firebasestorage.app',
    measurementId: 'G-H1F04PPR9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOH1hoSbqdrnwwWC0BD_vJUm6ABAzfSak',
    appId: '1:134493834023:android:6be4e2faa702964a45f702',
    messagingSenderId: '134493834023',
    projectId: 'love-88094',
    storageBucket: 'love-88094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApIPvBZcKPORUoed22TXX6e9ZLusnoOs',
    appId: '1:134493834023:ios:a4dcb003f0b457b545f702',
    messagingSenderId: '134493834023',
    projectId: 'love-88094',
    storageBucket: 'love-88094.firebasestorage.app',
    iosBundleId: 'com.example.thirdApp',
  );
}
