// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClAc-FvSjH2_SGiPkdOGflzrmMFWpZNIA',
    appId: '1:965485780400:web:a2aa936ce93ce2484d8a75',
    messagingSenderId: '965485780400',
    projectId: 'fir-app-7818b',
    authDomain: 'fir-app-7818b.firebaseapp.com',
    storageBucket: 'fir-app-7818b.firebasestorage.app',
    measurementId: 'G-L8LY1D45N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiV3ESVXRR2d00XDfbUxosigat5N7ePQ',
    appId: '1:965485780400:android:ca64bfb102edf2914d8a75',
    messagingSenderId: '965485780400',
    projectId: 'fir-app-7818b',
    storageBucket: 'fir-app-7818b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_6borISEupaim87znf_vxB4tDlir4DNI',
    appId: '1:965485780400:ios:14679fef7152db654d8a75',
    messagingSenderId: '965485780400',
    projectId: 'fir-app-7818b',
    storageBucket: 'fir-app-7818b.firebasestorage.app',
    androidClientId: '965485780400-ehbkn6veocic8oqdu8b2qoeg9338gscp.apps.googleusercontent.com',
    iosClientId: '965485780400-tlt7qorq8u6qv64j4a0ti341eqkt7b4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );
}
